# Generated by Django 5.0.3 on 2024-04-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersrelations',
            name='temp',
        ),
    ]
