# Generated by Django 5.0.3 on 2024-04-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promocodes',
            field=models.ManyToManyField(null=True, to='toyfactory_app.promocode'),
        ),
    ]
