# Generated by Django 5.0.3 on 2024-04-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'superuser'), ('CLIENT', 'client'), ('EMPLOYEE', 'employee')], max_length=50),
        ),
    ]
