# Generated by Django 5.0.3 on 2024-04-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0002_alter_order_promocodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
