# Generated by Django 5.0.3 on 2024-04-21 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0009_alter_feedback_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
