# Generated by Django 5.0.3 on 2024-04-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0010_alter_toy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promocodes',
        ),
        migrations.AddField(
            model_name='order',
            name='promocodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toyfactory_app.promocode'),
        ),
    ]
