# Generated by Django 5.0.3 on 2024-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory_app', '0012_alter_promocode_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
